import { jsPDF } from "jspdf";
import { DOC_TYPES, ISSUERS } from "../data/documents.js";

/* ============================================================================
   PDF GENERATION

   A document is rendered once, at the moment it is issued, and the resulting
   Blob is stored in the database next to its record. Viewing it later reads
   the stored bytes rather than re-rendering — so what the student downloads is
   byte-identical to what was issued, which is the point of an issued document.

   The letters are English-bodied (they address universities and embassies), so
   the standard PDF fonts cover them. Arabic body text would need an embedded
   font plus letter-shaping, which is why the Arabic appears only as the title
   line drawn from a transliteration, not as running text.
   ========================================================================== */

const MARGIN = 56;
const LINE = 17;

export function buildDocumentPdf(doc, user) {
  const d = DOC_TYPES[doc.kind];
  const iss = ISSUERS[d.issuer];
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const W = pdf.internal.pageSize.getWidth();
  let y = MARGIN;

  const text = (s, opts = {}) => {
    const { size = 11, style = "normal", gap = LINE, color = [30, 30, 30], align = "left" } = opts;
    pdf.setFont("helvetica", style);
    pdf.setFontSize(size);
    pdf.setTextColor(...color);
    const maxW = W - MARGIN * 2;
    const lines = pdf.splitTextToSize(String(s), maxW);
    lines.forEach((ln) => {
      pdf.text(ln, align === "right" ? W - MARGIN : MARGIN, y, { align });
      y += gap;
    });
  };

  const rule = (pad = 10) => {
    y += pad;
    pdf.setDrawColor(210, 206, 196);
    pdf.line(MARGIN, y, W - MARGIN, y);
    y += pad + 4;
  };

  /* ---- letterhead ---- */
  pdf.setFillColor(14, 122, 88);
  pdf.rect(0, 0, W, 6, "F");
  y = MARGIN + 6;
  text(iss.en.toUpperCase(), { size: 9, style: "bold", color: [14, 122, 88], gap: 14 });
  text("Kingdom of Saudi Arabia", { size: 9, color: [120, 120, 120], gap: 22 });

  text(d.title.en, { size: 18, style: "bold", color: [20, 40, 32], gap: 24 });
  rule();

  /* ---- reference block ---- */
  const issued = doc.date || "";
  text(`Reference:  ${doc.ref}`, { size: 10, style: "bold", gap: 15 });
  text(`Issued:     ${issued}`, { size: 10, gap: 15 });
  if (doc.term) text(`Term:       ${doc.term}`, { size: 10, gap: 15 });
  rule();

  /* ---- body ---- */
  text("To whom it may concern,", { size: 11, gap: 22 });

  const name = (user && user.name && user.name.en) || "";
  const nid = (user && user.national_id) || "";
  const degree = (user && user.degree && user.degree.en) || "";
  const uni = (user && user.university && user.university.en) || "";

  text(
    `This is to certify that ${name} (national ID ${nid}) is a recipient of the ` +
    `Custodian of the Two Holy Mosques Scholarship Program, sponsored by the Ministry ` +
    `of Education of Saudi Arabia, to pursue ${degree} at ${uni}.`,
    { size: 11, gap: 16 }
  );
  y += 8;

  if (doc.kind === "fgAdmission") {
    text(
      "The sponsor will cover full tuition and fees, a monthly living stipend, and health " +
      "insurance for the duration of the program. This letter may be relied upon for the " +
      "issuance of an admission offer and Form I-20, and for the student visa application.",
      { size: 11, gap: 16 }
    );
  } else if (doc.kind === "fgAcademic") {
    text(
      `The sponsor confirms payment of tuition and mandatory fees for the approved course ` +
      `load of the ${doc.term || "registered"} term. Charges outside the approved schedule ` +
      `are not covered by this guarantee.`,
      { size: 11, gap: 16 }
    );
  } else {
    text(
      "The award covers the full duration of the stated program, subject to continued " +
      "academic good standing and to the regulations of the scholarship programme.",
      { size: 11, gap: 16 }
    );
  }

  y += 26;
  text(iss.en, { size: 11, style: "bold", gap: 15 });
  text("Authorised electronically — no signature required.", { size: 9, color: [130, 130, 130], gap: 14 });

  /* ---- footer ---- */
  const H = pdf.internal.pageSize.getHeight();
  pdf.setDrawColor(220, 216, 206);
  pdf.line(MARGIN, H - 66, W - MARGIN, H - 66);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8);
  pdf.setTextColor(140, 140, 140);
  pdf.text(
    "Demo document generated by Rafeeq — an independent design concept. " +
    "Not affiliated with the Ministry of Education or any cultural mission. No real data is stored.",
    MARGIN, H - 48, { maxWidth: W - MARGIN * 2 }
  );
  pdf.text(doc.ref, W - MARGIN, H - 26, { align: "right" });

  return pdf.output("blob");
}

/* A stable, human-meaningful filename — this is what the browser saves as. */
export const pdfFilename = (doc) => `${doc.ref}-${DOC_TYPES[doc.kind].code}.pdf`;
